### ISSUE TITLE
Consider htslib

### ISSUE THREAD

**Issue by weinstockj** [auerlab/biolibc#1]
Suggesting here that htslib may be of interest: https://github.com/samtools/htslib 

Use of the API allows for accepting the binary BCF format so converting to raw text to parse is unnecessary. Most documentation is in comments in the header files: https://github.com/samtools/htslib/blob/develop/htslib/vcf.h

Josh

**Comment by outpaddling** [comment]
Thanks for the suggestion.  I was aware of htslib, but using their API would make the kind of  optimizations vcfio provides to vcf-split and ad2vcf very difficult.

**Comment by outpaddling** [comment]
To explain in more detail, vcf-split and ad2vcf are designed to run in parallel with bcftools/samtools and outrun their fastest use cases (simple "view" subcommands with optimal flags) in order to gain as much speedup as possible.  Using htslib, we might be able to build a stripped-down replacement for bcftools or samtools to gain even more, but my benchmarking of these tools and research on the BCF and CRAM formats have led me to believe that it would be a lot of work for a marginal gain.  For now, I'm content with the 1000-fold speedup that vcf-split provides over extracting one sample at a time via traditional approaches.
